version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_test
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: test_homeserver