// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Balance struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Balance     float64 `json:"balance"`
	Balanceaud  float64 `json:"balanceaud"`
	Pricebookid string  `json:"pricebookid"`
	Productid   string  `json:"productid"`
	Created     string  `json:"created"`
}

type Login struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type Transaction struct {
	ID      string  `json:"id"`
	Name    string  `json:"name"`
	Amount  float64 `json:"amount"`
	Date    string  `json:"date"`
	Type    string  `json:"type"`
	Created string  `json:"created"`
}
