CREATE TABLE IF NOT EXISTS tokens (
	id INTEGER NOT NULL PRIMARY KEY AUTO_INCREMENT,
	hash    BLOB NOT NULL,
	user_id INTEGER NOT NULL REFERENCES users ON DELETE CASCADE,
	expiry  DATETIME NOT NULL,
	scope   CHAR(255) NOT NULL
);